#!/usr/bin/env python3 
# -*- coding: utf-8 -*-

import rospy  
from hhcm_yolo_ros import YOLOInference

if __name__ == '__main__':

    node = YOLOInference()

    try:
        node.run()
    except rospy.ROSInterruptException:
        pass
   